- name: install and configure nginx
  tags: nginx_up
  block:
  - name: check if letsencrypt dir exist
    stat:
      path: "{{ letsencrypt_dir }}"
    become: true
    register: letsencrypt

  - name: install certbot via snapd
    snap:
      name:
        - certbot
      classic: true
    become: true
    when: letsencrypt.stat.exists == False

  - name: allow-nginx-traffic
    shell: sudo ufw allow 'Nginx Full'
    become: true
    when: letsencrypt.stat.exists == False

  - name: copy nginx config
    copy:
      src: gregentoo.com.conf
      dest:  /etc/nginx/conf.d/gregentoo.com.conf
    become: true
    when: letsencrypt.stat.exists == False

  - name: generate tls/ssl cert for server
    shell: /snap/bin/certbot --nginx --non-interactive --agree-tos --domains {{ letsencrypt_domain }} --email {{ letsencrypt_email }}
    become: true
    notify: nginx reloaded
    when: letsencrypt.stat.exists == False
    args:
      executable: /bin/bash
