- hosts: 
    - idealj
  roles:
    - role: tools
    - role: users
      default_user_password: TempPass4321
      users:
        - dummy
      admins:
        - admin
    - role: firewall
    - role: gcloud
      gcloud_bin_path: /usr/bin/gcloud
      gcloud_sa_folder: /root/.config/gcloud/credentials
      gcloud_sa_file_name: sa-key.json
      server_name: idealj
    - role: backup