virt_pkgs:
  - qemu-kvm
  - virtinst
  - bridge-utils
  - cpu-checker
  - libguestfs-tools
  - libvirt-daemon-system
  - apt-transport-https

virt_admin: gregory

sys_conf: /etc/sysctl.conf
cloud_init_network_config: /etc/network/interfaces.d/50-cloud-init
bridge_config: /etc/network/interfaces.d/51-bridge
cloud_init_disable_network: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

bridge_sysctl_values:
  - net.bridge.bridge-nf-call-ip6tables=0
  - net.bridge.bridge-nf-call-iptables=0
  - net.bridge.bridge-nf-call-arptables=0

main_interface: eno1
# Only needed for Debian 11 where bridge's default MAC address is not the one of the NI it is attached too. So we have to get the bound NI's MAC address
# and set it in the bridge config
#main_interface_mac_address: a4:bf:01:0d:c4:5c

libvirt_group: libvirt
qemu_conf: /etc/libvirt/qemu.conf
firewall_before_rules_file: /etc/ufw/before.rules
virt_working_dir: /home/gregory/virt
virt_disk_url: https://cloud.debian.org/images/cloud/buster/latest/debian-10-genericcloud-amd64.qcow2
virt_disks_path: /home/gregory/virt/disks
virt_config_path: /home/gregory/virt/config
virt_timezone: Europe/Berlin
bridge_name: br0
ssh_key_name: id_rsa.k8s-nodes

# master VM
master_id: 1
master_node_disk_path: /home/gregory/virt/disks/debian-10-genericcloud-amd64-master.qcow2
master_node_disk_size: 40
master_node_hostname: k8s-master
master_mac_address: 02:00:00:9c:9c:cc
master_ip: 51.83.150.197
master_network_config_host_path: /home/gregory/virt/config/00-net-config
master_domain_name: k8s-master
master_max_mem: 4194304
master_max_vcpus: 4
resolv_conf_path: /etc/

# worker VMs
worker_nodes:
  - { path: /home/gregory/virt/disks/debian-10-genericcloud-amd64-worker-0.qcow2, size: 40, network_config_file_name: "virt-interfaces-worker-0.j2", network_config_file_host_dest: "00-net-config-k8s-worker-0", hostname: "k8s-worker-0", max_vcpus: 4, max_mem: 4194304, ip: "51.83.147.42", mac_address: "02:00:00:0c:09:2d", id: 2, unique_guest_identifier: 2, fnr: 4 } # fnr is the line number in awk command parsing 'virsh net-dhcp-leases default'
  - { path: /home/gregory/virt/disks/debian-10-genericcloud-amd64-worker-1.qcow2, size: 40, network_config_file_name: "virt-interfaces-worker-1.j2", network_config_file_host_dest: "00-net-config-k8s-worker-1", hostname: "k8s-worker-1", max_vcpus: 4, max_mem: 4194304, ip: "51.83.179.16", mac_address: "02:00:00:3d:8f:41" , id: 3, unique_guest_identifier: 3, fnr: 3 }

# common to all VMs
main_net_interface: enp1s0
vm_netmask: 255.255.255.255
host_gateway_ip: 51.38.148.254