- name: install and configure borgbackup
  tags: backup_up
  block:
    - name: install borg packages
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      with_items: "{{ borg_packages }}"
      become: true

    - name: Create virtualenv for borg
      pip:
        name:
        - pip
        - setuptools
        state: latest
        virtualenv: /opt/borgmatic
        virtualenv_command: "{{ python_bin }} -m venv"
      become: true

    - name: Install Python Packages dependencies
      pip:
        name: "{{ borg_python_packages_dependencies }}"
        virtualenv: /opt/borgmatic
      when: borg_python_packages_dependencies is defined
      become: true

    - name: Install main Python Packages
      pip:
        name: "{{ borg_python_packages }}"
        virtualenv: /opt/borgmatic
      when: borg_python_packages is defined
      become: true

    - name: Create borgmatic command in /usr/local/bin
      copy:
        content: |
          #!/bin/bash
          . /opt/borgmatic/bin/activate
          borgmatic "$@"
        dest: /usr/local/bin/borgmatic
        owner: root
        group: root
        mode: "0755"
      become: true

    - name: Ensure /etc/borgmatic exists
      file:
        path: /etc/borgmatic
        state: directory
        mode: 0700
        owner: root
      become: true

    - name: Add Borgmatic configuration
      template:
        src: config.yaml.j2
        dest: "/etc/borgmatic/{{ borgmatic_config_name }}"
        mode: 0600
      become: true

    - name: Add cron-job for borgmatic
      cron:
        name: "{{ borgmatic_cron_name }}"
        hour: "{{ borgmatic_cron_hour }}"
        minute: "{{ borgmatic_cron_minute }}"
        user: "{{ admin }}"
        job: "sudo borgmatic -c /etc/borgmatic/{{ borgmatic_config_name }}"
      become_user: "{{ admin }}"
      become: true