- name: install and configure ufw firewall
  tags: firewall_up
  block:
  - name: install-ufw-firewall
    apt:
      name: ufw
      state: present
    register: apt_ufw
    retries: 3
    delay: 10
    until: apt_ufw is success
    become: true

  - name: enable-ufw-firewall
    ufw:
      state: enabled
      policy: deny
    become: true

  - name: allow some ports on host
    ufw:
      rule: allow
      port: "{{ item }}"
    become: true
    with_items: "{{ allowed_ports_host }}"
    when: inventory_hostname in groups["kvm_host"]

  - name: allow some ports on VMs
    ufw:
      rule: allow
      port: "{{ item }}"
    become: true
    with_items: "{{ allowed_ports_vms }}"
    when: inventory_hostname in groups["kvm_guests"]