- name: Deploy Drone stack
  tags: drone_install
  block:
    - name: Get infos on Drone server container
      docker_container_info:
        name: "{{ drone_server_container }}"
      become: true
      register: drone_server

    - name: Start Drone services
      docker_compose:
        project_src: "/home/{{ admin }}/{{ drone_dir }}"
      become: true
      when: drone_server.exists == False

  when: inventory_hostname in groups["kvm_host"]