- name: install k8s components
  include_tasks: k8s-install.yml
  tags: k8s_install

- name: uninstall k8s components
  include_tasks: k8s-uninstall.yml
  tags: k8s_uninstall

- name: install openebs components
  include_tasks: openebs-install.yml
  tags: openebs_install

- name: install nginx ingress controller
  include_tasks: nginx-ingress-controller-install.yml
  tags: nginx_ingress_controller_install

- name: install cert-manager and configure ssl termination for domain
  include_tasks: cert-manager-install.yml
  tags: cert_manager_install

- name: install prometheus stack
  include_tasks: prometheus-stack-install.yml
  tags: prometheus_stack_install
