- name: users
  block:
  - name: create users
    user:
      name: "{{ item }}"
      state: present
      password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
      shell: "{% if users_credentials[item].shell is defined %}{{ users_credentials[item].shell }}{%else %}/bin/bash{% endif %}"
    become: true
    tags:
      - users_up
    with_items: "{{ users + admins }}"

  - name: .ssh exists with correct perms
    file:
      dest: "/home/{{ item }}/.ssh"
      state: directory
      mode: 0755
      owner: "{{ item }}"
    become: true
    tags:
      - users_up
    with_items: "{{ users + admins }}"

  - name: Check if ~/.ssh/authorized_keys file exists
    stat:
      path: "/home/{{ item }}/.ssh/authorized_keys"
    register: auth_keys_file
    become: true
    tags:
      - users_up
    with_items: "{{ users + admins }}"

  - name: Create ~/.ssh/authorized_keys if not exists
    file:
      path: "/home/{{ item[1] }}/.ssh/authorized_keys"
      state: touch
      owner: "{{ item[1] }}"
      group: "{{ item[1] }}"
      mode: 0600
    become: true
    tags:
      - users_up
    when: item[0].stat.exists == False
    with_together:
      - "{{ auth_keys_file.results }}"
      - "{{ users + admins }}"

  - name: user can login with their ssh pub key
    blockinfile:
      dest: "/home/{{ item }}/.ssh/authorized_keys"
      block: "{{ users_credentials[item].ssh_pub_keys | join('\n')}}"
    become: true
    tags:
      - users_up
    with_items: "{{ users + admins }}"

  - name: delete users
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    become: true
    tags:
      - users_down
    with_items: "{{ users_to_delete }}"

  - name: admins are in the sudo group
    user:
      name: "{{ item }}"
      groups: sudo
      append: true
    become: true
    tags:
      - users_up
    with_items: "{{ admins }}"
