- name: Create users
  include_tasks: users-create.yml
  tags: users_up

- name: Delete users
  include_tasks: users-delete.yml
  tags:
    - users_down

- name: Setup oh-my-zsh
  include_tasks: oh-my-zsh-install.yml
  tags: zsh_up

- name: Uninstall oh-my-zsh
  include_tasks: oh-my-zsh-uninstall.yml
  tags:
    - zsh_down