- name: uninstall ufw firewall
  tags: firewall_down
  block:
  - name: disable-ufw-firewall
    ufw:
      state: disabled
    become: true

  - name: uninstall-ufw-firewall
    apt:
      name: ufw
      state: present
    register: apt_ufw
    retries: 3
    delay: 10
    until: apt_ufw is success
    become: true