- name: install system packages
  include_tasks: sys-pkgs-install.yml
  tags: sys_pkgs_up

- name: uninstall system packages
  include_tasks: sys-pkgs-uninstall.yml
  tags:
    - sys_pkgs_down

- name: install ufw firewall
  include_tasks: firewall-install.yml
  tags: firewall_up

- name: uninstall ufw firewall
  include_tasks: firewall-uninstall.yml
  tags:
    - firewall_down

- name: install Docker components
  include_tasks: docker-install.yml
  tags:
    - docker_up

- name: uninstall Docker components
  include_tasks: docker-uninstall.yml
  tags:
    - docker_down

- name: install and configure Nginx
  include_tasks: nginx-install.yml
  tags:
    - nginx_up