- name: create disk images
  tags:
    - virt_disks_remove
  block:
  - name: remove node disks directory
    file:
      path: "{{ virt_working_dir }}"
      state: absent
    become_user: "{{ virt_admin }}"
    become: true
  when: inventory_hostname in groups["kvm_host"]