- name: install required virt packages
  tags:
    - virt_pkgs_up
  block:
  - name: install-virtualization-packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    register: apt_virt_pkgs
    retries: 3
    delay: 10
    until: apt_virt_pkgs is success
    become: true
    with_items: "{{ virt_pkgs }}"