- name: create vms
  tags:
    - virt_vm_remove
  block:
  - name: list running VMs
    virt:
      command: list_vms
      state: running
    register: running_vms
    become_user: "{{ virt_admin }}"
    become: true

  - name: stop vms
    virt:
      name: "{{ item }}"
      command: shutdown
      state: shutdown
    become_user: "{{ virt_admin }}"
    become: true
    with_items: "{{ running_vms['list_vms'] }}"

  - name: undefine vms
    virt:
      name: "{{ item }}"
      command: undefine
    become_user: "{{ virt_admin }}"
    become: true
    with_items: "{{ running_vms['list_vms'] }}"