- name: borg-backup
  block:
  - name: Install borgbackup
    apt:
      name: borgbackup
      update_cache: yes
    become: yes

  - name: Install borgmatic
    pip:
      name: borgmatic
      extra_args: --user

  - name: Check if /root/.local/bin is added to the $PATH
    lineinfile:
      state: absent
      path: ~/.zshrc
      regexp: "export PATH=/home/{{ admin }}/.local/bin:$PATH"
    check_mode: true
    register: check

  - name: Add /home/{{ admin }}/root/.local/bin to $PATH if not done yet
    lineinfile:
      state: present
      path: ~/.zshrc
      line: "export PATH=/home/{{ admin }}/.local/bin:$PATH"
    when: check.found == 0

  - name: Source admin shell config
    shell: source "/home/{{ admin }}/{{ shell_config }}"
    args:
      executable: "{{ shell_path }}"
    become: yes
      
